apiVersion: v1
kind: ServiceAccount
metadata:
  name: ebpf-exporter
  namespace: ebpf-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ebpf-exporter
  namespace: ingress-nginx-external
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ebpf-exporter
  namespace: ingress-nginx-external
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ebpf-exporter
subjects:
- kind: ServiceAccount
  name: ebpf-exporter
  namespace: ebpf-exporter
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  labels:
    k8s-app: ebpf-exporter
  name: ebpf-exporter
  namespace: ebpf-exporter
spec:
  selector:
    matchLabels:
      k8s-app: ebpf-exporter
  template:
    metadata:
      labels:
        k8s-app: ebpf-exporter
    spec:
      serviceAccountName: ebpf-exporter
      containers:
      - name: ebpf-exporter
        image: giorio94/ebpf-exporter:v0.2.2
        args:
        - --config.file=/config/ebpf-config.yaml
        - --nginx.namespace=ingress-nginx-external
        - --nginx.node=$(NODE_NAME)
        - --debug
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        ports:
        - containerPort: 9435
          name: metrics
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /healthz
            port: metrics
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        volumeMounts:
        - mountPath: /config
          name: ebpf-config
          readOnly: true
        - mountPath: /lib/modules
          name: lib-modules
          readOnly: true
        - mountPath: /sys/kernel/debug
          name: sys-kernel-debug
        securityContext:
          privileged: true
      nodeSelector:
        kubernetes.io/os: linux
      volumes:
      - configMap:
          name: ebpf-config
        name: ebpf-config
      - hostPath:
          path: /lib/modules
          type: Directory
        name: lib-modules
      - hostPath:
          path: /sys/kernel/debug
          type: Directory
        name: sys-kernel-debug
  updateStrategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: ebpf-exporter
  name: ebpf-exporter
  namespace: ebpf-exporter
spec:
  clusterIP: None
  ports:
  - name: metrics
    port: 9435
    targetPort: metrics
  selector:
    k8s-app: ebpf-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: ebpf-exporter
  name: ebpf-exporter
  namespace: ebpf-exporter
spec:
  endpoints:
  - port: metrics
    scheme: http
  selector:
    matchLabels:
      k8s-app: ebpf-exporter
